### ISSUE TITLE
Follow Tab - Scrolling

### ISSUE THREAD

**Issue by nullfunction** [seriousbears/seriousbears#13]
The Follow tab doesn't seem to allow scrolling, but it appears that there's another element hidden under the bottom rail of the site: http://i.imgur.com/EdMc0mJ.png

**Comment by nullfunction** [comment]
Steps to reproduce:
1. Open www.seriousbears.net in Chrome.
2. Click on the play icon.
3. Wait until the music starts playing.
4. Move your cursor to the top portion of the page (where the notification of loading audio is displayed). Note that the black scrollbar appears.
5. Move your mouse toward the bottom of the page. Note that the black scrollbar disappears.

**Comment by tylerstraub** [comment]
Fixed by implementing a different scroll bar plugin by Malihu.. totally beautiful.
